---
- name: Instalando o puppet no ubuntu
  apt:
    name: puppet-agent
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Instalando o puppet no centos
  yum:
    name: puppet-agent
    state: present
  when: ansible_distribution == "CentOS"


- name: Colocando puppet na variavel PATH
  lineinfile: 
    path: /etc/profile
    line: "export PATH=$PATH:/opt/puppetlabs/bin/"
    create: yes   
