---
- name: Configurando repositorio do puppet
  get_url:
    url: https://apt.puppetlabs.com/puppet5-release-xenial.deb
    dest: /tmp/puppet.deb
  when: ansible_distribution == "Ubuntu"

- name: Instalando Repositorio no Ubuntu
  apt:
    deb: /tmp/puppet.deb
  when: ansible_distribution == "Ubuntu"


- name: Configurando repositorio do puppet centos
  get_url:
    url: https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
    dest: /tmp/puppet.rpm
  when: ansible_distribution == "CentOS"

- name: Instalando Repositorio no centos
  yum:
    name: /tmp/puppet.rpm
  when: ansible_distribution == "CentOS"

