---
- name: Garantindo configuracao
  hosts: dev
  tasks:
     # instalar 2 pacotes - Sao: apache2, php7
     # habilitar o modulo php: a2enmod php
     # colocar um index.php dentro de /var/www/html com o conteudo "hello php!"
     # <? echo "hello php!"; ?>

    - name: Instalando apache2
      apt:
        name: apache2
        state: present

    - name: Restartando o Apache
      service:
        name: apache2
        state: restarted

    - name: Instalando php7.0
      apt:
        name: php7.0
        state: present

    - name: libapache2-mod-php7.0
      apt:
        name: libapache2-mod-php7.0
        state: present

    - name: Instalando a2enmod php
      shell: a2enmod php7.0
       

    - name: Colocando Index Hello php
      shell: echo "<?php echo 'hello php!'; ?>" > /var/www/html/index.php
        
       
