---
- name: LAMP CENTOS
  hosts: all
  tasks:
  - name: Instalando o Apache no centos
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS"

  - name: Instalando o apache no ubuntu
    apt:
     name: apache2
     state: present
    when: ansible_distribution == "Ubuntu"

  handlers:
    - name: restart apache
      service:
        name: apache2
        start: running

    - name: restart httpd
      service:
        name: httpd
        state: restarted
